//
//  UserAlbumsScenePresenter.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 20-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserAlbumsScenePresentationLogic {
    func presentAlbums(response: UserAlbumsScene.LoadAlbums.Response)
}

class UserAlbumsScenePresenter: UserAlbumsScenePresentationLogic {
    weak var viewController: UserAlbumsSceneDisplayLogic?

    // MARK: Do something

    func presentAlbums(response: UserAlbumsScene.LoadAlbums.Response) {
        if response.success {
            let viewModel = UserAlbumsScene.LoadAlbums.ViewModel(
                albums: response.albums.map { AlbumViewModel(id: $0.id, title: $0.title) }
            )
            viewController?.displayAlbums(viewModel: viewModel)
        } else {
            viewController?.displayError()
        }
    }
}
