//
//  UserAlbumsSceneWorker.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 20-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UserAlbumsSceneWorker {
    func fetchAlbumsForUser(id: Int, completion: @escaping (_ success: Bool, _ albums: Albums) -> Void) {
        let albumsBaseUrl = Constants.API.albums
        let url = albumsBaseUrl.urlByAddingParameters([
            Constants.Parameters.userId: String(id)
        ])

        ApiClient.get(
            url,
            success: { data in
                do {
                    let albums = try JSONDecoder().decode(Albums.self, from: data)
                    completion(true, albums)
                } catch {
                    completion(false, [])
                }
            },
            failure: { error in
                completion(false, [])
            }
        )
    }
}
