//
//  UserAlbumsSceneViewController.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 20-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserAlbumsSceneDisplayLogic: class {
    func displaySomething(viewModel: UserAlbumsScene.Something.ViewModel)
}

class UserAlbumsSceneViewController: UIViewController, UserAlbumsSceneDisplayLogic {
    var interactor: UserAlbumsSceneBusinessLogic?
    var router: (NSObjectProtocol & UserAlbumsSceneRoutingLogic & UserAlbumsSceneDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = UserAlbumsSceneInteractor()
        let presenter = UserAlbumsScenePresenter()
        let router = UserAlbumsSceneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        title = "Álbumes"
        view.backgroundColor = Colors.ViewController.background
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething() {
        let request = UserAlbumsScene.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: UserAlbumsScene.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
