//
//  UserAlbumsSceneInteractor.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 20-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserAlbumsSceneBusinessLogic {
    func loadAlbums(request: UserAlbumsScene.LoadAlbums.Request)
}

protocol UserAlbumsSceneDataStore {
    var selectedAlbumId: Int { get set }
    var userId: Int { get set }
}

class UserAlbumsSceneInteractor: UserAlbumsSceneBusinessLogic, UserAlbumsSceneDataStore {
    var presenter: UserAlbumsScenePresentationLogic?
    var worker: UserAlbumsSceneWorker? = UserAlbumsSceneWorker()
    var userId: Int = 0
    var albums: Albums = []
    var selectedAlbumId = 0

    // MARK: Do something

    func loadAlbums(request: UserAlbumsScene.LoadAlbums.Request) {
        worker?.fetchAlbumsForUser(id: userId) { success, albums in
            self.albums = albums
            let response = UserAlbumsScene.LoadAlbums.Response(
                success: success,
                albums: albums
            )
            self.presenter?.presentAlbums(response: response)
        }
    }
}
