//
//  UserDetailsSceneViewController.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 19-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsSceneDisplayLogic: class {
    func displaySomething(viewModel: UserDetailsScene.Something.ViewModel)
}

class UserDetailsSceneViewController: UIViewController, UserDetailsSceneDisplayLogic {
    var interactor: UserDetailsSceneBusinessLogic?
    var router: (NSObjectProtocol & UserDetailsSceneRoutingLogic & UserDetailsSceneDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = UserDetailsSceneInteractor()
        let presenter = UserDetailsScenePresenter()
        let router = UserDetailsSceneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        title = (interactor as? UserDetailsSceneDataStore)?.user?.name
        view.backgroundColor = Colors.ViewController.background
        doSomething()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doSomething() {
        let request = UserDetailsScene.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: UserDetailsScene.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
