//
//  UserDetailsSceneInteractor.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 19-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsSceneBusinessLogic {
    func doSomething(request: UserDetailsScene.Something.Request)
}

protocol UserDetailsSceneDataStore {
    var user: User? { get set }
}

class UserDetailsSceneInteractor: UserDetailsSceneBusinessLogic, UserDetailsSceneDataStore {
    var presenter: UserDetailsScenePresentationLogic?
    var worker: UserDetailsSceneWorker?
    var user: User?

    // MARK: Do something

    func doSomething(request: UserDetailsScene.Something.Request) {
        worker = UserDetailsSceneWorker()
        worker?.doSomeWork()

        let response = UserDetailsScene.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
