//
//  UserDetailsSceneModels.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 19-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserDetailsScene {
    // MARK: Use cases
    enum MarkAsFavorite {
        struct Request {}
    }

    enum UpdatedData {
        struct Request {}

        struct Response {
            let screenTitle: String?
            let user: User?
        }

        struct ViewModel {
            let screenTitle: String?
            let name: String?
            let phone: String?
        }
    }
}
