//
//  UserDetailsSceneInteractor.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 19-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsSceneBusinessLogic {
    func presentUserData(request: UserDetailsScene.UpdatedData.Request)
    func toggleFavoriteStatus(request: UserDetailsScene.MarkAsFavorite.Request)
}

protocol UserDetailsSceneDataStore {
    var user: User? { get set }
}

class UserDetailsSceneInteractor: UserDetailsSceneBusinessLogic, UserDetailsSceneDataStore {
    var presenter: UserDetailsScenePresentationLogic?
    var worker: UserDetailsSceneWorker?
    var user: User?

    // MARK: Do something

    func presentUserData(request: UserDetailsScene.UpdatedData.Request) {
        let response = UserDetailsScene.UpdatedData.Response(
            screenTitle: user?.name
        )
        presenter?.presentUpdatedData(response: response)
    }

    func toggleFavoriteStatus(request: UserDetailsScene.MarkAsFavorite.Request) {
        let currentStatus = user?.isFavorite ?? false
        user?.isFavorite = !currentStatus

        let response = UserDetailsScene.UpdatedData.Response(
            screenTitle: user?.name
        )
        presenter?.presentUpdatedData(response: response)
    }
}
