//
//  UserDetailsSceneRouter.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 19-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsSceneRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UserDetailsSceneDataPassing {
    var dataStore: UserDetailsSceneDataStore? { get }
}

class UserDetailsSceneRouter: NSObject, UserDetailsSceneRoutingLogic, UserDetailsSceneDataPassing {
    weak var viewController: UserDetailsSceneViewController?
    var dataStore: UserDetailsSceneDataStore?

    // MARK: Routing

}
