//
//  UserDetailsScenePresenter.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 19-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailsScenePresentationLogic {
    func presentSomething(response: UserDetailsScene.Something.Response)
}

class UserDetailsScenePresenter: UserDetailsScenePresentationLogic {
    weak var viewController: UserDetailsSceneDisplayLogic?

    // MARK: Do something

    func presentSomething(response: UserDetailsScene.Something.Response) {
        let viewModel = UserDetailsScene.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
