//
//  AlbumDetailsInteractor.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 23-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumDetailsBusinessLogic {
    func loadPhotos(request: AlbumDetails.FetchPhotos.Request)
}

protocol AlbumDetailsDataStore {
    var albumId: Int { get set }
    var albumTitle: String? { get set }
}

class AlbumDetailsInteractor: AlbumDetailsBusinessLogic, AlbumDetailsDataStore {
    var presenter: AlbumDetailsPresentationLogic?
    var worker: AlbumDetailsWorker? = AlbumDetailsWorker()

    var albumId: Int = 0
    var albumTitle: String?
    var photos: Photos = []

    // MARK: Do something

    func loadPhotos(request: AlbumDetails.FetchPhotos.Request) {
        worker?.fetchPhotosForAlbum(id: albumId) { success, photos in
            self.photos = photos
            let response = AlbumDetails.FetchPhotos.Response(
                success: success && photos.count > 0,
                photos: photos
            )
            self.presenter?.presentPhotos(response: response)
        }
    }
}
