//
//  AlbumDetailsModels.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 23-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AlbumDetails {
    // MARK: Use cases

    enum FetchPhotos {
        struct Request {}

        struct Response {
            let success: Bool
            let photos: Photos
        }

        struct ViewModel {
            let photos: [PhotosViewModel]
        }
    }
}
