//
//  AlbumDetailsWorker.swift
//  photoalbumsexample
//
//  Created by Alejandro Melo Domínguez on 23-02-20.
//  Copyright (c) 2020 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AlbumDetailsWorker {
    func fetchPhotosForAlbum(id: Int, completion: @escaping (_ success: Bool, _ photos: Photos) -> Void) {
        let photosBaseUrl = Constants.API.photos
        let url = photosBaseUrl.urlByAddingParameters([
            Constants.Parameters.albumId: String(id)
        ])

        ApiClient.get(
            url,
            success: { data in
                do {
                    let photos = try JSONDecoder().decode(Photos.self, from: data)
                    completion(true, photos)
                } catch {
                    completion(false, [])
                }
            },
            failure: { error in
                completion(false, [])
            }
        )
    }
}
